### ISSUE TITLE
Failure while compiling

### ISSUE THREAD

**Issue by geilerloui** [leegao/readme2tex#18]
Hi,
I have just installed the package I have tried with the following command

python -m readme2tex --output README.md readme.md

and I have the following error message

**Comment by Shiling42** [comment]
I encountered the same problem. In my case, it is caused by using \begin{split} \end{split}.

**Comment by EduMota** [comment]
I have the same problem.

**Comment by JARVIS-AI** [comment]
Have similar problem,
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/site-packages/readme2tex/__main__.py", line 160, in <module>
    args.bustcache)
  File "/usr/local/lib/python2.7/site-packages/readme2tex/render.py", line 144, in render
    name = hashlib.md5(equation.encode('utf-8')).hexdigest()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1: ordinal not in range(128)
```
```
python -m readme2tex --nocdn --output --file.md file-edited.md
```

**Comment by msedalatzadeh** [comment]
I got similar error after running

`C:\Users\name\Documents\GitHub\readme2tex-master>py -m readme2tex --output README.md READOTHER.md`


>Traceback (most recent call last): File "C:\Users\name\Documents\GitHub\readme2tex-master\readme2tex\render.py", line 301, in render giturl = check_output(['git', 'remote', '-v']).strip().decode('utf-8').splitlines()[0] IndexError: list index out of range

**Comment by Tejesh-Raut** [comment]
`Traceback (most recent call last):
  File "C:\Users\Tejes\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Tejes\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\users\tejes\desktop\temp\readme2tex\readme2tex\__main__.py", line 148, in <module>
    render(
  File "c:\users\tejes\desktop\temp\readme2tex\readme2tex\render.py", line 174, in render
    svg, dvi, name = rendertex(engine, equation, packages, temp_dir, block)
  File "c:\users\tejes\desktop\temp\readme2tex\readme2tex\render.py", line 44, in rendertex
    svg = check_output(
  File "C:\Users\Tejes\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\Tejes\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Tejes\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Tejes\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified`

**Comment by Tejesh-Raut** [comment]
I had a similar problem. Resolved it by ensuring `dvisvgm` is in path

**Comment by zhangddjs** [comment]
I meet the same situation, can author help solve this issue?
