### ISSUE TITLE
No such file or directory: 'dvisvgm'

### ISSUE THREAD

**Issue by bmy4415** [leegao/readme2tex#24]
Hello, I just installed this package and I tried to complie my README.md.
After I command `python -m readme2tex --output result.md README.md`, I got this error message but I don't know how to handle it
```
'$cost=\sum { { (y-\bar { y } ) }^{ 2 } } +\lambda \sum { { \left| W \right|  }^{ 2 } }$' has warnings during compilation. See /var/folders/zb/9sv0pm4x7v1c9ng44rpbqs7r0000gn/T/readme2tex-k3308sx3/6cfc9fee460f304e0df2af7fcf3336f8
Traceback (most recent call last):
  File "/Users/bmy4415/.pyenv/versions/3.5.4/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/bmy4415/.pyenv/versions/3.5.4/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/bmy4415/.pyenv/versions/3.5.4/lib/python3.5/site-packages/readme2tex/__main__.py", line 160, in <module>
    args.bustcache)
  File "/Users/bmy4415/.pyenv/versions/3.5.4/lib/python3.5/site-packages/readme2tex/render.py", line 167, in render
    svg, dvi, name = rendertex(engine, equation, packages, temp_dir, block)
  File "/Users/bmy4415/.pyenv/versions/3.5.4/lib/python3.5/site-packages/readme2tex/render.py", line 44, in rendertex
    ['dvisvgm', '-v0', '-a', '-n', '-s', dvi])
  File "/Users/bmy4415/.pyenv/versions/3.5.4/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/Users/bmy4415/.pyenv/versions/3.5.4/lib/python3.5/subprocess.py", line 383, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/bmy4415/.pyenv/versions/3.5.4/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/Users/bmy4415/.pyenv/versions/3.5.4/lib/python3.5/subprocess.py", line 1289, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'dvisvgm'
```

I think there are some faults in my LATEX code but not sure.
Can anybody help me?

**Comment by tonyduan** [comment]
You need to install [dvisvgm](https://dvisvgm.de) onto your system (it does not come pre-installed with this package).
