### ISSUE TITLE
Traceback when using --add-git-hook

### ISSUE THREAD

**Issue by siddharthist** [leegao/readme2tex#5]
The directory I was working in was a git repository:
```
code/coq-typeclass-hierarchy > python -m readme2tex --add-git-hook
Traceback (most recent call last):
  File "/nix/store/p4fqqhllhyj90njg2sksz8qrgzlzs193-python-2.7.13/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/nix/store/p4fqqhllhyj90njg2sksz8qrgzlzs193-python-2.7.13/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/nix/store/qgfi4pzf9awf5axakp2f0kj4xf7r7grn-readme2tex/lib/python2.7/site-packages/readme2tex/__main__.py", line 163, in <module>
    assert os.path.exists(".git")
AssertionError
```

**Comment by leegao** [comment]
Hey @siddharthist, thanks for the issue report. I'm a bit swamped for the next two days so I might not get a chance to look closer at these issues. Are you in the top-level directory?

**Comment by leegao** [comment]
Also great to see someone else in the PL field :)

**Comment by siddharthist** [comment]
@leegao I think this was my error, I wasn't in a git repo like I thought 😓 Anyway, it's probably better to print an error message than a traceback 😄 No rush, thanks for the response!

**Comment by leegao** [comment]
Totally forgot about this; this has been fixed a few PRs ago!
